export type Product = {
  id: string;
  sku: string;
  name: string;
  price: number;
  category: "Rings" | "Necklaces" | "Earrings" | "Bracelets";
  material: "Yellow Gold" | "White Gold" | "Platinum" | "Rose Gold" | "Silver";
  image: string;
  description: string;
  featured: boolean;
  bestSeller: boolean;
};

export const products: Product[] = [
  {
    id: "1",
    sku: "RN-AUR-01",
    name: "Aurum Diamond Solitaire",
    price: 2450,
    category: "Rings",
    material: "Yellow Gold",
    image: "/images/ring_aurum.png",
    description: "A breathtaking premium gold ring featuring a single, brilliant-cut clear diamond. The perfect symbol of eternal love.",
    featured: true,
    bestSeller: true,
  },
  {
    id: "2",
    sku: "NK-LUN-01",
    name: "Luna Emerald Pendant",
    price: 1850,
    category: "Necklaces",
    material: "Yellow Gold",
    image: "/images/necklace_luna.png",
    description: "An elegant emerald pendant set in 18k yellow gold, resting gracefully on a delicate chain. Exquisite and timeless.",
    featured: true,
    bestSeller: false,
  },
  {
    id: "3",
    sku: "ER-SOL-01",
    name: "Solitaire Diamond Studs",
    price: 3200,
    category: "Earrings",
    material: "White Gold",
    image: "/images/earrings_solitaire.png",
    description: "Classic diamond solitaire earrings set in premium white gold. Unmatched sparkle and sophistication.",
    featured: false,
    bestSeller: true,
  },
  {
    id: "4",
    sku: "BR-ELA-01",
    name: "Elara Chain Bracelet",
    price: 1150,
    category: "Bracelets",
    material: "Yellow Gold",
    image: "/images/bracelet_elara.png",
    description: "A thick, luxurious gold chain link bracelet. A statement piece that elevates any ensemble.",
    featured: true,
    bestSeller: true,
  },
  {
    id: "5",
    sku: "RN-TIA-01",
    name: "Imperial Tiara Ring",
    price: 4500,
    category: "Rings",
    material: "Platinum",
    image: "/images/ring_tiara.png",
    description: "Intricately detailed diamond crown tiara ring crafted in solid platinum. Fit for royalty.",
    featured: true,
    bestSeller: false,
  },
  {
    id: "6",
    sku: "RN-GLD-02",
    name: "Classic Gold Band",
    price: 650,
    category: "Rings",
    material: "Yellow Gold",
    image: "/images/ring_aurum.png",
    description: "A timeless, unadorned solid gold band. The essence of purity and minimalist elegance.",
    featured: false,
    bestSeller: true,
  },
  {
    id: "7",
    sku: "RN-EMC-01",
    name: "Emerald Cut Platinum",
    price: 5200,
    category: "Rings",
    material: "Platinum",
    image: "/images/ring_emerald_cut.png",
    description: "A stunning emerald-cut clear diamond set in a sleek platinum band. Maximum clarity and brilliance.",
    featured: true,
    bestSeller: false,
  },
  {
    id: "8",
    sku: "NK-PRL-01",
    name: "Vintage Pearl Strand",
    price: 1200,
    category: "Necklaces",
    material: "Silver",
    image: "/images/necklace_pearl.png",
    description: "An elegant strand of white pearls secured with a delicate silver clasp. A vintage classic.",
    featured: false,
    bestSeller: true,
  },
  {
    id: "9",
    sku: "ER-EMD-01",
    name: "Emerald Drop Earrings",
    price: 2800,
    category: "Earrings",
    material: "White Gold",
    image: "/images/earrings_emerald.png",
    description: "Pair of vivid emerald gemstone drop earrings set in white gold. A stunning pop of color.",
    featured: true,
    bestSeller: false,
  },
  {
    id: "10",
    sku: "BR-TNS-01",
    name: "Diamond Tennis Bracelet",
    price: 6500,
    category: "Bracelets",
    material: "White Gold",
    image: "/images/bracelet_diamond_tennis.png",
    description: "A continuous line of brilliant diamonds set in white gold. The ultimate statement of luxury.",
    featured: true,
    bestSeller: true,
  },
  {
    id: "11",
    sku: "RN-HAL-01",
    name: "Radiant Halo Ring",
    price: 3800,
    category: "Rings",
    material: "White Gold",
    image: "/images/ring_halo.png",
    description: "A round clear diamond surrounded by a sparkling halo of smaller diamonds. Breathtaking radiance.",
    featured: true,
    bestSeller: true,
  },
  {
    id: "12",
    sku: "NK-EMR-02",
    name: "Teardrop Emerald Pendant",
    price: 2100,
    category: "Necklaces",
    material: "White Gold",
    image: "/images/necklace_emerald_teardrop.png",
    description: "A magnificent teardrop-shaped emerald suspended from a delicate white gold chain.",
    featured: true,
    bestSeller: false,
  },
  {
    id: "13",
    sku: "ER-HOP-01",
    name: "Diamond Hoop Earrings",
    price: 1950,
    category: "Earrings",
    material: "White Gold",
    image: "/images/earrings_hoop_silver.png",
    description: "Classic white gold hoop earrings encrusted with sparkling diamonds. Everyday elegance.",
    featured: false,
    bestSeller: true,
  },
  {
    id: "14",
    sku: "BR-EMC-01",
    name: "Emerald Cuff Bracelet",
    price: 3400,
    category: "Bracelets",
    material: "Silver",
    image: "/images/bracelet_emerald_cuff.png",
    description: "A bold silver cuff bracelet featuring embedded emerald stones. A striking modern design.",
    featured: true,
    bestSeller: false,
  },
  {
    id: "15",
    sku: "RN-VEM-01",
    name: "Vintage Emerald Ring",
    price: 4100,
    category: "Rings",
    material: "Platinum",
    image: "/images/ring_vintage_emerald.png",
    description: "An heirloom-quality vintage design featuring a rich emerald center surrounded by diamond accents.",
    featured: false,
    bestSeller: true,
  }
];
